---
driver:
  name: vagrant

driver_config:
  require_chef_omnibus: 12.5.1

provisioner:
  name: chef_zero
  client_rb:
    audit_mode: :enabled

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - diskdemo
